### ISSUE TITLE
Metadata not all showing up

### ISSUE THREAD

**Issue by abbymullen** [abbymullen/civilwar_bookworm#1]
The metadata in the jsoncatalog file isn't all showing up in the actual interface. Only a handful of authors are showing up, for instance, and no recipients.

**Comment by bmschmidt** [comment]
How about now? I just reset it. It doesn't look like there are many recipients at all, at least with more than 20 letters to them which is the cutoff.

**Comment by abbymullen** [comment]
Looks much better now. Recipient I wasn't so concerned about, since
probably most of these documents are recipient-less. Thanks!

On Sun, May 17, 2015 at 12:10 AM, Benjamin Schmidt <notifications@github.com
